import { NgModule } from '@angular/core';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Routes } from '@angular/router';

import { PrivacyComponent } from './privacy/privacy.component';
import { CookiepolicyComponent } from './cookiepolicy/cookiepolicy.component';
import { TermsofuseComponent } from './termsofuse/termsofuse.component';
import { AboutusComponent } from './aboutus/aboutus.component';
import { SettingsComponent } from './settings/settings.component';
import { SubscriptionComponent } from './subscription/subscription.component';
import { HelpComponent } from './help/help.component';
import { RegisterComponent } from './register/register.component';
import { LoginComponent } from './login/login.component';
import { LoginDetailComponent } from './login-detail/login-detail.component';
import { LanguageComponent } from './language/language.component';
import { ComicbookComponent } from './comicbook/comicbook.component';
// import { DashboardComponent } from './dashboard/dashboard.component';
import { HomeComponent } from './home/home.component';
import { MovieListComponent } from './movie-list/movie-list.component';
import { MovieDetailComponent } from './movie-detail/movie-detail.component';
import { SearchDetailComponent } from './search-detail/search-detail.component';
// import { AppLandingComponent } from './app-landing/app-landing.component';
// import { DashboardDetailComponent } from './dashboard-detail/dashboard-detail.component';
import { ActionDetailComponent } from './action-detail/action-detail.component';
import { ActionListComponent } from './action-list/action-list.component';
import { AdventureListComponent } from './adventure-list/adventure-list.component';
import { AdventureDetailComponent } from './adventure-detail/adventure-detail.component';
import { ComedyListComponent } from './comedy-list/comedy-list.component';
import { ComedyDetailComponent } from './comedy-detail/comedy-detail.component';
import { DramaListComponent } from './drama-list/drama-list.component';
import { DramaDetailComponent } from './drama-detail/drama-detail.component';
import { FictionListComponent } from './fiction-list/fiction-list.component';
import { FictionDetailComponent } from './fiction-detail/fiction-detail.component';
import { HistoricalListComponent } from './historical-list/historical-list.component';
import { HistoricalDetailComponent } from './historical-detail/historical-detail.component';
import {ResetpasswordComponent} from './resetpassword/resetpassword.component';
import {ResetemailComponent} from './resetemail/resetemail.component';
import {MakepaymentsComponent} from './makepayments/makepayments.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';

const routes: Routes = [
  {path: '', redirectTo: '/', pathMatch: 'full'},
  {path: '', component: HomeComponent},
  // {path: 'applanding', component: AppLandingComponent},
  {path: 'movies', component: MovieListComponent},
  // {path: 'dashmovies', component: DashboardComponent},
  // {path: 'dashmovies/:slug', component: DashboardDetailComponent},
  {path: '3comic book',  component: ComicbookComponent},
  {path: 'language', component: LanguageComponent},
  {path: 'search', component: SearchDetailComponent},
  {path: 'login',  component: LoginComponent},
  {path: 'register', component: RegisterComponent},
  {path: 'users/:makepremium', component: MakepaymentsComponent},
  {path: 'about us', component: AboutusComponent},
  {path: 'settings', component: SettingsComponent},
  {path: 'subscription', component: SubscriptionComponent},
  {path: 'help', component: HelpComponent},
  {path: 'privacy', component: PrivacyComponent},
  {path: 'cookiepolicy', component: CookiepolicyComponent},
  {path: 'termsofuse', component: TermsofuseComponent},
  {path: 'movies/:slug', component: MovieDetailComponent},
  {path: 'action', component: ActionListComponent},
  {path: 'action/:slug', component: ActionDetailComponent},
  {path: 'adventure', component: AdventureListComponent},
  {path: 'adventure/:slug', component: AdventureDetailComponent},
  {path: 'comedy', component: ComedyListComponent},
  {path: 'resetemail', component: ResetemailComponent},
  {path: 'resetpassword', component: ResetpasswordComponent},
  {path: 'comedy/:slug', component: ComedyDetailComponent},
  {path: 'drama', component: DramaListComponent},
  {path: 'drama/:slug', component: DramaDetailComponent},
  {path: 'fiction', component: FictionListComponent},
  {path: 'fiction/:slug', component: FictionDetailComponent},
  {path: 'historical', component: HistoricalListComponent},
  {path: 'historical:slug', component: HistoricalDetailComponent},
];

@NgModule({
  imports: [NativeScriptRouterModule.forRoot(routes)],
  exports: [NativeScriptRouterModule]
})
export class AppRoutingModule { }
