import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from '@src/app/app-routing.module.tns';
import { AppComponent } from '@src/app/app.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule, HttpClientXsrfModule } from '@angular/common/http';
import { HttpClient } from '@angular/common/http';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';

import { NguCarouselModule } from '@ngu/carousel';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

// third party imports
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import { CarouselModule } from 'ngx-bootstrap/carousel';

import { MovieService } from '@src/app/movies/movies.service';

import { AboutusComponent } from '@src/app/aboutus/aboutus.component';
import { ComicbookComponent } from '@src/app/comicbook/comicbook.component';
import { CookiepolicyComponent } from '@src/app/cookiepolicy/cookiepolicy.component';
// import { DashboardComponent } from '@src/app/dashboard/dashboard.component';
import { HelpComponent } from '@src/app/help/help.component';
import { HomeComponent } from '@src/app/home/home.component';
import { LanguageComponent } from '@src/app/language/language.component';
import { LoginComponent } from '@src/app/login/login.component';
import { LoginDetailComponent } from '@src/app/login-detail/login-detail.component';
import { MovieListComponent } from '@src/app/movie-list/movie-list.component';
import { MovieDetailComponent } from '@src/app/movie-detail/movie-detail.component';
import { PrivacyComponent } from '@src/app/privacy/privacy.component';
import { Routes, RouterModule } from '@angular/router';
import { RegisterComponent } from '@src/app/register/register.component';
import { SafePipe } from '@src/app/utility/safe.pipe';
import { SettingsComponent } from '@src/app/settings/settings.component';
import { SearchComponent } from '@src/app/search/search.component';
import { SearchDetailComponent } from '@src/app/search-detail/search-detail.component';
import { SubscriptionComponent } from '@src/app/subscription/subscription.component';
import { TermsofuseComponent } from '@src/app/termsofuse/termsofuse.component';
// import { CarouselComponent } from '@src/app/carousel/carousel.component';
// import { DashboardDetailComponent } from '@src/app/dashboard-detail/dashboard-detail.component';
// import { AppLandingComponent } from '@src/app/app-landing/app-landing.component';
import { AdventureListComponent } from '@src/app/adventure-list/adventure-list.component';
import { AdventureDetailComponent } from '@src/app/adventure-detail/adventure-detail.component';
import { DramaListComponent } from '@src/app/drama-list/drama-list.component';
import { DramaDetailComponent } from '@src/app/drama-detail/drama-detail.component';
import { ActionListComponent } from '@src/app/action-list/action-list.component';
import { ActionDetailComponent } from '@src/app/action-detail/action-detail.component';
import { ComedyListComponent } from '@src/app/comedy-list/comedy-list.component';
import { ComedyDetailComponent } from '@src/app/comedy-detail/comedy-detail.component';
import { HistoricalListComponent } from '@src/app/historical-list/historical-list.component';
import { HistoricalDetailComponent } from '@src/app/historical-detail/historical-detail.component';
import { FictionListComponent } from '@src/app/fiction-list/fiction-list.component';
import { FictionDetailComponent } from '@src/app/fiction-detail/fiction-detail.component';
// import { StreamactionListComponent } from '@src/app/streamaction-list/streamaction-list.component';
// import { StreamactionDetailComponent } from '@src/app/streamaction-detail/streamaction-detail.component';
// import { StreamadventureListComponent } from '@src/app/streamadventure-list/streamadventure-list.component';
// import { StreamadventureDetailComponent } from '@src/app/streamadventure-detail/streamadventure-detail.component';
// import { StreamdramaListComponent } from '@src/app/streamdrama-list/streamdrama-list.component';
// import { StreamdramaDetailComponent } from '@src/app/streamdrama-detail/streamdrama-detail.component';
// import { StreamcomedyListComponent } from '@src/app/streamcomedy-list/streamcomedy-list.component';
// import { StreamcomedyDetailComponent } from '@src/app/streamcomedy-detail/streamcomedy-detail.component';
// import { StreamfictionListComponent } from '@src/app/streamfiction-list/streamfiction-list.component';
// import { StreamfictionDetailComponent } from '@src/app/streamfiction-detail/streamfiction-detail.component';
// import { StreamhistoricalListComponent } from '@src/app/streamhistorical-list/streamhistorical-list.component';
// import { StreamhistoricalDetailComponent } from '@src/app/streamhistorical-detail/streamhistorical-detail.component';
import { NotFoundComponent } from '@src/app/not-found/not-found.component';
import { StatusComponent } from '@src/app/status/status.component';
import { AuthComponent } from '@src/app/auth/auth.component';
import { StatusDetailComponent } from '@src/app/status-detail/status-detail.component';
import { StatusCreateComponent } from '@src/app/status-create/status-create.component';
// import { MovieraterComponent } from '@src/app/movierater/movierater.component';
// import { AdminComponent } from '@src/app/admin/admin.component';
import { AuthLogoutComponent } from '@src/app/auth-logout/auth-logout.component';
// import { AuthSignUpComponent } from '@src/app/auth-sign-up/auth-sign-up.component';
// import { SignUpComponent } from '@src/app/sign-up/sign-up.component';
// import { SignInComponent } from '@src/app/sign-in/sign-in.component';
import { ActionThrillerListComponent } from '@src/app/action-thriller-list/action-thriller-list.component';
import { ActionThrillerDetailComponent } from '@src/app/action-thriller-detail/action-thriller-detail.component';
import { AdventureThrillerListComponent } from '@src/app/adventure-thriller-list/adventure-thriller-list.component';
import { AdventureThrillerDetailComponent } from '@src/app/adventure-thriller-detail/adventure-thriller-detail.component';
import { ActionRealListComponent } from '@src/app/action-real-list/action-real-list.component';
import { ActionRealDetailComponent } from '@src/app/action-real-detail/action-real-detail.component';
import { AdventureRealListComponent } from '@src/app/adventure-real-list/adventure-real-list.component';
import { AdventureRealDetailComponent } from '@src/app/adventure-real-detail/adventure-real-detail.component';
import { ComedyThrillerListComponent } from '@src/app/comedy-thriller-list/comedy-thriller-list.component';
import { ComedyThrillerDetailComponent } from '@src/app/comedy-thriller-detail/comedy-thriller-detail.component';
import { ComedyRealListComponent } from '@src/app/comedy-real-list/comedy-real-list.component';
import { ComedyRealDetailComponent } from '@src/app/comedy-real-detail/comedy-real-detail.component';
import { DramaThrillerListComponent } from '@src/app/drama-thriller-list/drama-thriller-list.component';
import { DramaThrillerDetailComponent } from '@src/app/drama-thriller-detail/drama-thriller-detail.component';
import { DramaRealListComponent } from '@src/app/drama-real-list/drama-real-list.component';
import { DramaRealDetailComponent } from '@src/app/drama-real-detail/drama-real-detail.component';
import { FictionThrillerListComponent } from '@src/app/fiction-thriller-list/fiction-thriller-list.component';
import { FictionThrillerDetailComponent } from '@src/app/fiction-thriller-detail/fiction-thriller-detail.component';
import { FictionRealListComponent } from '@src/app/fiction-real-list/fiction-real-list.component';
import { FictionRealDetailComponent } from '@src/app/fiction-real-detail/fiction-real-detail.component';
import { HistoricalThrillerListComponent } from '@src/app/historical-thriller-list/historical-thriller-list.component';
import { HistoricalThrillerDetailComponent } from '@src/app/historical-thriller-detail/historical-thriller-detail.component';
import { HistoricalRealListComponent } from '@src/app/historical-real-list/historical-real-list.component';
import { HistoricalRealDetailComponent } from '@src/app/historical-real-detail/historical-real-detail.component';
import { ResetpasswordComponent } from '@src/app/resetpassword/resetpassword.component';
import { ResetemailComponent } from '@src/app/resetemail/resetemail.component';
import { MakepaymentsComponent } from '@src/app/makepayments/makepayments.component';




// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

const routes: Routes = [
  {path: 'movies/:slug', component: MovieListComponent},
  {path: 'movies/:slug', component: MovieDetailComponent},
  {path: 'movies/:slug', redirectTo: 'movies/:slug', pathMatch: 'full'},
  {path: 'language', component: LanguageComponent},
];

@NgModule({
  declarations: [
    AppComponent,
    MovieListComponent,
    MovieDetailComponent,
    SafePipe,
    HomeComponent,
    // DashboardComponent,
    ComicbookComponent,
    LanguageComponent,
    LoginComponent,
    LoginDetailComponent,
    RegisterComponent,
    AboutusComponent,
    SettingsComponent,
    SubscriptionComponent,
    HelpComponent,
    PrivacyComponent,
    CookiepolicyComponent,
    TermsofuseComponent,
    SearchComponent,
    SearchDetailComponent,
    LoginDetailComponent,
    // CarouselComponent,
    AutoGeneratedComponent,
    // DashboardDetailComponent,
    // AppLandingComponent,
    AdventureListComponent,
    AdventureDetailComponent,
    DramaListComponent,
    DramaDetailComponent,
    ActionListComponent,
    ActionDetailComponent,
    ComedyListComponent,
    ComedyDetailComponent,
    HistoricalListComponent,
    HistoricalDetailComponent,
    FictionListComponent,
    FictionDetailComponent,
    // StreamactionListComponent,
    // StreamactionDetailComponent,
    // StreamadventureListComponent,
    // StreamadventureDetailComponent,
    // StreamdramaListComponent,
    // StreamdramaDetailComponent,
    // StreamcomedyListComponent,
    // StreamcomedyDetailComponent,
    // StreamfictionListComponent,
    // StreamfictionDetailComponent,
    // StreamhistoricalListComponent,
    // StreamhistoricalDetailComponent,
    NotFoundComponent,
    StatusComponent,
    AuthComponent,
    StatusDetailComponent,
    StatusCreateComponent,
    // MovieraterComponent,
    // AdminComponent,
    AuthLogoutComponent,
    // AuthSignUpComponent,
    // SignUpComponent,
    // SignInComponent,
    ActionThrillerListComponent,
    ActionThrillerDetailComponent,
    AdventureThrillerListComponent,
    AdventureThrillerDetailComponent,
    ActionRealListComponent,
    ActionRealDetailComponent,
    AdventureRealListComponent,
    AdventureRealDetailComponent,
    ComedyThrillerListComponent,
    ComedyThrillerDetailComponent,
    ComedyRealListComponent,
    ComedyRealDetailComponent,
    DramaThrillerListComponent,
    DramaThrillerDetailComponent,
    DramaRealListComponent,
    DramaRealDetailComponent,
    FictionThrillerListComponent,
    FictionThrillerDetailComponent,
    FictionRealListComponent,
    FictionRealDetailComponent,
    HistoricalThrillerListComponent,
    HistoricalThrillerDetailComponent,
    HistoricalRealListComponent,
    HistoricalRealDetailComponent,
    ResetpasswordComponent,
    ResetemailComponent,
    MakepaymentsComponent,

  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    CarouselModule.forRoot(),
    BsDropdownModule.forRoot(),
    BrowserModule,
    HttpClientModule,
    FormsModule,
    ReactiveFormsModule,
    NguCarouselModule,
    NgbModule,
    // HttpClientXsrfModule.withOptions({ cookieName: 'csrftoken', headerName: 'X-CSRFToken' })
  ],
  providers: [MovieService],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule {
  constructor(router: RouterModule) {
  }
}
